[package]
name = "oak_proto_rust"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
std = []

[dependencies]
micro_rpc = { workspace = true }
prost = { workspace = true, default-features = false, features = [
  "prost-derive",
] }
prost-types = { version = "*", default-features = false }

[build-dependencies]
micro_rpc_build = { workspace = true }
prost-build = { workspace = true }
pbjson-build = { version = "*", optional = true }
