[package]
name = "oak_session"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
aead = { version = "*", default-features = false }
anyhow = { version = "*", default-features = false }
itertools = { version = "*", default-features = false }
oak_crypto = { workspace = true }
oak_proto_rust = { workspace = true }
prost = { version = "*", default-features = false }

[dev-dependencies]
mockall = { version = "*", default-features = false }
