[package]
name = "oak_multi_process_test"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
log = "*"
oak_restricted_kernel_sdk = { workspace = true }
oak_restricted_kernel_interface = { workspace = true }

[[bin]]
name = "oak_multi_process_test"
test = false
bench = false
