[package]
name = "oak_containers_hello_world_web_client"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "*"
async-trait = "*"
base64 = "*"
js-sys = "*"
getrandom = { version = "*", features = ["js"] }
oak_attestation_verification = { workspace = true }
oak_client = { default-features = false, path = "../../../oak_client" }
oak_proto_rust = { workspace = true }
prost = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
web-sys = { version = "*", features = [
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
] }
