[package]
name = "machine_learning"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rusty-machine = "0.5.4"
rand = "0.6.1"
oak = { path = "../../rust/oak" }
