[package]
name = "oak_micro_rpc"
version = "0.1.0"
authors = ["Project Oak Team <project-oak-team@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = []
std = []

[lib]
path = "lib.rs"

[dependencies]
micro_rpc = { workspace = true }
oak_proto_rust = { workspace = true }
prost = { workspace = true, default-features = false, features = [
  "prost-derive",
] }

[build-dependencies]
micro_rpc_build = { workspace = true }
