[package]
name = "oak_restricted_kernel_orchestrator"
version = "0.1.0"
authors = ["Juliette Pluto <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
default = ["exchange_evidence"]
exchange_evidence = ["oak_attestation"]

[dependencies]
oak_channel = { workspace = true }
oak_dice = { workspace = true }
oak_attestation = { workspace = true, optional = true }
oak_restricted_kernel_dice = { workspace = true }
oak_proto_rust = { workspace = true }
log = "*"
prost = { workspace = true, default-features = false }
prost-types = { version = "*", default-features = false }
