[package]
name = "oak_session_wasm"
version = "0.1.0"
authors = ["Juliette Pluto <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "*"
js-sys = "*"
getrandom = { version = "*", features = ["js"] }
oak_session = { workspace = true }
oak_proto_rust = { workspace = true }
prost = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
