[package]
name = "machine_learning"
version = "0.1.0"
authors = ["Tiziano Santoro <tzn@google.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
rusty-machine = "0.5.4"
wasm-bindgen = "0.2"
rand = { version = "0.6.1", features = ["wasm-bindgen"] }
oak = { path = "../../" }
